# Generated by Django 5.1.3 on 2024-12-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('Dno', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=50)),
                ('D_loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('Eno', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Hiredate', models.DateField(auto_now=True)),
                ('Dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('Mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
